# Generated by Django 2.1.1 on 2018-09-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=128, verbose_name='Nazwisko')),
                ('phone', models.IntegerField(verbose_name='Numer telefonu')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('to', models.ForeignKey(on_delete='CASCADE', to='salon_managment.Customer')),
            ],
        ),
    ]
