# Generated by Django 2.1.1 on 2018-09-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon_managment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerhistory',
            old_name='to',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='customerhistory',
            name='date',
        ),
    ]
